# Generated by Django 5.2.6 on 2025-09-04 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка для категории по URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=50, verbose_name='ИНН')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма долга')),
                ('debt_type', models.CharField(max_length=50, verbose_name='Тип долга')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('closed', 'Закрыт'), ('pending', 'В ожидании')], max_length=50, verbose_name='Статус')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Долг',
                'verbose_name_plural': 'Долги',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('guide_type', models.CharField(choices=[('loan', 'Ссуда'), ('grant', 'Грант'), ('subsidy', 'Субсидия')], max_length=20, verbose_name='Тип гайда')),
                ('link', models.URLField(verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Гайд',
                'verbose_name_plural': 'Гайды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('leader_position', models.CharField(max_length=50, verbose_name='Должность')),
                ('leader_image', models.ImageField(upload_to='leaders/', verbose_name='Фото')),
                ('leader_mail', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('leader_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('region', models.CharField(blank=True, choices=[('Toshkent', 'Toshkent'), ('Toshkent-viloyati', 'Toshkent-viloyati'), ('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Farg`ona', 'Farg`ona'), ('Jizzax', 'Jizzax'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ('Samarqand', 'Samarqand'), ('Surxondaryo', 'Surxondaryo'), ('Sirdaryo', 'Sirdaryo'), ('Xorazm', 'Xorazm'), ('Qoraqalpog`iston', 'Qoraqalpog`iston')], max_length=50, verbose_name='Регион')),
                ('region_link', models.URLField(blank=True, verbose_name='Ссылка яндкес карты на местоположение')),
            ],
            options={
                'verbose_name': 'Лидер',
                'verbose_name_plural': 'Лидеры',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(upload_to='partners/', verbose_name='Изображение')),
                ('link', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('kaa', 'Karakalpak')], max_length=5, verbose_name='Язык')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news_app.category')),
            ],
            options={
                'verbose_name': 'Перевод категории',
                'verbose_name_plural': 'Переводы категорий',
                'unique_together': {('category', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='GuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('kaa', 'Karakalpak')], max_length=5, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('short_title', models.CharField(blank=True, max_length=100, verbose_name='Короткий заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news_app.guide')),
            ],
            options={
                'verbose_name': 'Перевод гайда',
                'verbose_name_plural': 'Переводы гайдов',
                'unique_together': {('guide', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='NewsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('kaa', 'Karakalpak')], max_length=5, verbose_name='Язык')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('short_title', models.CharField(max_length=100, verbose_name='Короткий заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.TextField(verbose_name='Короткое описание')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_app.category', verbose_name='Категория')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news_app.news')),
            ],
            options={
                'verbose_name': 'Перевод новости',
                'verbose_name_plural': 'Переводы новостей',
                'unique_together': {('news', 'lang')},
            },
        ),
    ]
